const products = [
  {
    image: "lamp-1",
    altImage: "lamp-4",
    title: "Встраиваемый светильник Markt",
    price: "3 490",
    oldPrice: "5 060",
    isPromo: true,
  },
  {
    image: "lamp-2",
    altImage: "lamp-4",
    title: "Линейный светильник ARG",
    price: "6 700",
    oldPrice: "6 060", 
    isPromo: false,
  },
  {
    image: "lamp-3",
    altImage: "lamp-4",
    title: "Светодиодный светильник",
    price: "5 060",
    oldPrice: "6 060",
    isPromo: true,
  },
  {
    image: "lamp-1",
    altImage: "lamp-4",
    title: "Встраиваемый светильник Markt",
    price: "3 490",
    oldPrice: "6 060",
    isPromo: false,
  },
  {
    image: "lamp-2",
    altImage: "lamp-4",
    title: "Линейный светильник ARG",
    price: "6 700",
    oldPrice: "6 060",
    isPromo: true,
  },
  {
    image: "lamp-3",
    altImage: "lamp-4",
    title: "Светодиодный светильник",
    price: "5 060",
    oldPrice: "6 060",
    isPromo: false,
  },
  {
    image: "lamp-1",
    altImage: "lamp-4",
    title: "Встраиваемый светильник Markt",
    price: "3 490",
    oldPrice: "6 060",
    isPromo: true,
  },
  {
    image: "lamp-2",
    altImage: "lamp-4",
    title: "Линейный светильник ARG",
    price: "6 700",
    oldPrice: "6 060",
    isPromo: false,
  },
];
